### ISSUE TITLE
Front end doesn't install

### ISSUE THREAD

**Issue by DarkTrick** [Spyna/push-notification-demo#4]
Front end (both) don't `npm install` because they use deprecated libraries.

node version: 18.6

This is the output for `npm install` in front-end:
```
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated eslint-loader@2.2.1: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

npm ERR! code 1
npm ERR! path /path/to/project/push-notification-demo/front-end/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c /var/folders/cy/80bt07ss5r93z029n_wf2ds40000gn/T/postinstall65974249.sh
npm ERR! Building: /opt/homebrew/Cellar/node/18.6.0/bin/node /path/to/project/push-notification-demo/front-end/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/opt/homebrew/Cellar/node/18.6.0/bin/node',
npm ERR! gyp verb cli   '/path/to/project/push-notification-demo/front-end/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.6.0 | darwin | arm64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:211:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:211:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:211:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:211:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (/path/to/project/push-notification-demo/front-end/node_modules/node-gyp/lib/configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/path/to/project/push-notification-demo/front-end/node_modules/node-gyp/lib/configure.js:406:16)
npm ERR! gyp ERR! stack     at F (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:68:16)
npm ERR! gyp ERR! stack     at E (/path/to/project/push-notification-demo/front-end/node_modules/which/which.js:80:29)
npm ERR! gyp ERR! stack     at /path/to/project/push-notification-demo/front-end/node_modules/which/which.js:89:16
npm ERR! gyp ERR! stack     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /path/to/project/push-notification-demo/front-end/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:211:21)
npm ERR! gyp ERR! System Darwin 21.5.0
npm ERR! gyp ERR! command "/opt/homebrew/Cellar/node/18.6.0/bin/node" "/path/to/project/push-notification-demo/front-end/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /path/to/project/push-notification-demo/front-end/node_modules/node-sass
npm ERR! gyp ERR! node -v v18.6.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2022-07-28T14_02_56_913Z-debug-0.log
```

Error message for `npm install` in **front-end-react**
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: front-end-react@0.1.0
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   eslint@"^6.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0" from @typescript-eslint/parser@1.13.0
npm ERR! node_modules/@typescript-eslint/parser
npm ERR!   @typescript-eslint/parser@"1.13.0" from the root project
npm ERR!   peer @typescript-eslint/parser@"^1.9.0" from @typescript-eslint/eslint-plugin@1.13.0
npm ERR!   node_modules/@typescript-eslint/eslint-plugin
npm ERR!     @typescript-eslint/eslint-plugin@"1.13.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/users/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
```

**Comment by Spyna** [comment]
Could you please provide the node version you are using to run the install command? 
Which front-end do you mean? the `front-end` of `front-end-react`. 
I can install and run the front-end using node `v12.x` (using nvm)

**Comment by DarkTrick** [comment]
Thank you very much for the quick response!

I added more information to the first message. Unfortunately I have the feeling that the error is a different one than the one I got 3 days ago when I filed the report (stupid of me to not have included logs back then)

**Comment by thisfardi** [comment]
how to fix this ?
![image](https://github.com/Spyna/push-notification-demo/assets/38723240/30019db6-b370-4d74-8d1d-1fc55a290a82)
thanks before
